apiVersion: v1
kind: PersistentVolume
metadata:
  name: internet-monitor-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/leoadmin/internet-monitor-k8s/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internet-monitor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: internet-monitor-pv
